# Generated by Django 2.1.7 on 2019-11-23 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
