# Generated by Django 2.1.7 on 2019-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('Created', 'Created'), ('Closed', 'Closed')], default='Created', max_length=10),
        ),
    ]
