# Generated by Django 2.1.7 on 2019-11-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_campaign_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('alt', models.DecimalField(decimal_places=16, max_digits=22)),
                ('localize_names', models.CharField(max_length=300)),
                ('prov_org', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
    ]
