# Generated by Django 2.1.7 on 2019-11-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
