# Generated by Django 2.1.7 on 2019-11-26 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0002_auto_20191124_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
