# Generated by Django 2.1.7 on 2019-11-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0003_peak_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='localize_names',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='prov_org',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='status',
        ),
    ]
