# Generated by Django 2.1.7 on 2019-11-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_date_posted'),
        ('peak', '0004_auto_20191126_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='campaign_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
            preserve_default=False,
        ),
    ]
