# Generated by Django 2.1.7 on 2019-11-27 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0005_peak_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='alt',
            field=models.DecimalField(decimal_places=16, default=23232, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='peak',
            name='fileJson',
            field=models.FileField(default=232, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=111, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='localize_names',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='lon',
            field=models.DecimalField(decimal_places=16, default=11, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='prov_org',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
