# Generated by Django 2.1.7 on 2019-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0007_auto_20191127_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='fileJson',
            field=models.FileField(upload_to='profile_pics'),
        ),
    ]
