# Generated by Django 2.1.7 on 2019-11-27 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0008_auto_20191127_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='peak',
            name='localize_names',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
