# Generated by Django 2.1.7 on 2019-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0009_auto_20191127_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
