# Generated by Django 2.1.7 on 2019-11-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0010_auto_20191127_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='alt',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=22),
        ),
        migrations.AddField(
            model_name='peak',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=22),
        ),
        migrations.AddField(
            model_name='peak',
            name='lon',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=22),
        ),
        migrations.AddField(
            model_name='peak',
            name='provenance_org',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='peak',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
