# Generated by Django 2.1.7 on 2019-11-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0012_auto_20191128_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='status',
            field=models.BooleanField(choices=[('annotate', 1), ('notAnnotate', 0)], default=1),
        ),
    ]
