# Generated by Django 2.1.7 on 2019-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0014_auto_20191128_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='status',
            field=models.BooleanField(choices=[('1', 'Annotate'), ('0', 'Do not Annotate')], default=True),
        ),
    ]
