# Generated by Django 2.1.7 on 2019-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0015_auto_20191128_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
