# Generated by Django 2.1.7 on 2019-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0016_auto_20191128_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peak',
            name='provenance_org',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
