# Generated by Django 2.1.7 on 2019-12-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0017_auto_20191128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='peak_id',
            field=models.IntegerField(default=3243532),
            preserve_default=False,
        ),
    ]
