# Generated by Django 2.1.7 on 2020-02-14 12:44

from django.db import migrations, models
import peak.validators


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0019_auto_20191219_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=16, default=0.0, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='peak',
            name='fileJson',
            field=models.FileField(upload_to='profile_pics', validators=[peak.validators.validate_file_extension]),
        ),
    ]
