# Generated by Django 2.1.7 on 2019-11-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peak', '0017_auto_20191128_1656'),
        ('campaign', '0003_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peak_annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('w_localize_names', models.CharField(blank=True, max_length=300, null=True)),
                ('w_provenance_org', models.CharField(blank=True, max_length=1000, null=True)),
                ('w_alt', models.DecimalField(decimal_places=16, default=0.0, max_digits=22)),
                ('peak_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peak.Peak')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_activities.Campaign_enrollment')),
            ],
        ),
    ]
