# Generated by Django 2.1.7 on 2019-12-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0002_peak_annotations_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak_annotations',
            name='status',
        ),
        migrations.RemoveField(
            model_name='peak_annotations',
            name='w_alt',
        ),
        migrations.RemoveField(
            model_name='peak_annotations',
            name='w_localize_names',
        ),
        migrations.RemoveField(
            model_name='peak_annotations',
            name='w_provenance_org',
        ),
    ]
