# Generated by Django 2.1.7 on 2019-12-03 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0003_auto_20191203_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak_annotations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
