# Generated by Django 2.1.7 on 2019-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0004_auto_20191203_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak_annotations',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
