# Generated by Django 2.1.7 on 2019-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0005_peak_annotations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak_annotations',
            name='valued',
            field=models.BooleanField(default=False),
        ),
    ]
