# Generated by Django 2.1.7 on 2019-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0006_peak_annotations_valued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak_annotations',
            name='valued',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
