# Generated by Django 2.1.7 on 2019-12-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0007_auto_20191205_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak_annotations',
            name='valued',
            field=models.BooleanField(blank=True, choices=[(True, True), (False, False)], null=True),
        ),
    ]
