# Generated by Django 2.1.7 on 2019-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0008_auto_20191218_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak_annotations',
            name='valued',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
