# Generated by Django 2.1.7 on 2019-12-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0011_auto_20191226_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak_annotations',
            name='provenance_org',
        ),
    ]
