# Generated by Django 2.1.7 on 2020-01-18 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0013_auto_20200117_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak_annotations',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
